use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    assert_app_icon();
    prepare_tray_icon();
    generate_runtime_modules();
    tauri_build::build();
}

fn runtime_src_dir(manifest_dir: &Path) -> PathBuf {
    manifest_dir.join("../runtime")
}

fn runtime_modules_manifest(manifest_dir: &Path) -> PathBuf {
    manifest_dir.join("../runtime/index.json")
}

fn is_runtime_module_file(file_name: &str) -> bool {
    file_name.ends_with(".js")
        && !file_name.ends_with(".test.js")
        && !file_name.starts_with("_test")
}

fn generate_runtime_modules() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let runtime_dir = runtime_src_dir(&manifest_dir);
    let manifest_path = runtime_modules_manifest(&manifest_dir);

    println!("cargo:rerun-if-changed={}", manifest_path.display());
    println!("cargo:rerun-if-changed={}", runtime_dir.display());

    let manifest_raw = fs::read_to_string(&manifest_path)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", manifest_path.display()));
    let bundle_modules: Vec<String> = serde_json::from_str(&manifest_raw).unwrap_or_else(|error| {
        panic!(
            "failed to parse runtime modules manifest {}: {error}",
            manifest_path.display()
        )
    });

    let mut standalone_modules = Vec::new();
    for entry in fs::read_dir(&runtime_dir).unwrap_or_else(|error| {
        panic!(
            "failed to read runtime source directory {}: {error}",
            runtime_dir.display()
        )
    }) {
        let entry = entry.unwrap_or_else(|error| panic!("failed to read module entry: {error}"));
        let path = entry.path();
        let file_name = path
            .file_name()
            .and_then(|value| value.to_str())
            .unwrap_or("");
        if !is_runtime_module_file(file_name) {
            continue;
        }
        if bundle_modules.iter().any(|module| module == file_name) {
            continue;
        }
        standalone_modules.push(file_name.to_string());
    }
    standalone_modules.sort();

    let mut generated =
        String::from("// @generated by build.rs from runtime/index.json and runtime/*.js\n");
    generated.push_str("pub const RUNTIME_MODULE_SOURCES: &[&str] = &[\n");
    for file_name in &bundle_modules {
        let module_path = runtime_dir.join(file_name);
        if !module_path.is_file() {
            panic!(
                "runtime module listed in {} was not found: {}",
                manifest_path.display(),
                module_path.display()
            );
        }
        println!("cargo:rerun-if-changed={}", module_path.display());
        generated.push_str(&format!(
            "    include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../runtime/{file_name}\")),\n"
        ));
    }
    generated.push_str("];\n\n");
    generated.push_str("pub const STANDALONE_RUNTIME_SCRIPTS: &[&str] = &[\n");
    for file_name in &standalone_modules {
        let module_path = runtime_dir.join(file_name);
        println!("cargo:rerun-if-changed={}", module_path.display());
        generated.push_str(&format!(
            "    include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../runtime/{file_name}\")),\n"
        ));
    }
    generated.push_str("];\n");

    let generated_path = out_dir.join("runtime_modules.rs");
    fs::write(&generated_path, generated)
        .unwrap_or_else(|error| panic!("failed to write {}: {error}", generated_path.display()));
}

fn assert_app_icon() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let app_icon = manifest_dir.join("icons/icon.png");

    if !app_icon.is_file() {
        panic!(
            "App icon not found: {} (add your Codex Helper icon PNG here)",
            app_icon.display()
        );
    }

    let _ = fs::read(&app_icon)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", app_icon.display()));

    println!("cargo:rerun-if-changed={}", app_icon.display());
}

/// Build `icons/tray-menu.png` from `icons/tray.png` for menu bar embedding.
///
/// Edit `tray.png` (any size, black + transparent). Cargo embeds the generated
/// 44×44 asset via `include_image!` so icon changes rebuild reliably.
fn prepare_tray_icon() {
    const MENU_BAR_PX: &str = "44";

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let icons_dir = manifest_dir.join("icons");
    let tray_source = icons_dir.join("tray.png");
    let tray_flat = icons_dir.join("tray-flat.png");
    let tray_scaled = icons_dir.join("tray-menu-scaled.png");
    let tray_menu = icons_dir.join("tray-menu.png");

    if !tray_source.is_file() {
        panic!(
            "Tray icon source not found: {} (black shape on transparent PNG)",
            tray_source.display()
        );
    }

    // Track source; read bytes so cargo always knows this build step depends on it.
    let _ = fs::read(&tray_source)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", tray_source.display()));

    println!("cargo:rerun-if-changed={}", tray_source.display());

    // Interlaced PNG (Adam7) breaks Tauri tray embedding; flatten before resize.
    deinterlace_png(&tray_source, &tray_flat);

    let fit = Command::new("sips")
        .arg("-Z")
        .arg(MENU_BAR_PX)
        .arg(&tray_flat)
        .arg("--out")
        .arg(&tray_scaled)
        .status()
        .unwrap_or_else(|error| panic!("failed to run sips for tray icon fit: {error}"));
    if !fit.success() {
        panic!(
            "failed to fit tray icon {} within {MENU_BAR_PX}px",
            tray_flat.display()
        );
    }

    let pad = Command::new("sips")
        .arg("--padToHeightWidth")
        .arg(MENU_BAR_PX)
        .arg(MENU_BAR_PX)
        .arg(&tray_scaled)
        .arg("--out")
        .arg(&tray_menu)
        .status()
        .unwrap_or_else(|error| panic!("failed to run sips for tray icon pad: {error}"));
    let _ = fs::remove_file(&tray_flat);
    let _ = fs::remove_file(&tray_scaled);
    if !pad.success() {
        panic!(
            "failed to pad tray icon {} to {MENU_BAR_PX}x{MENU_BAR_PX}",
            tray_scaled.display()
        );
    }

    println!("cargo:rerun-if-changed={}", tray_menu.display());
}

fn deinterlace_png(source: &Path, dest: &Path) {
    let tiff = dest.with_extension("tif");
    let to_tiff = Command::new("sips")
        .arg("-s")
        .arg("format")
        .arg("tiff")
        .arg(source)
        .arg("--out")
        .arg(&tiff)
        .status()
        .unwrap_or_else(|error| panic!("failed to run sips for tray deinterlace: {error}"));
    if !to_tiff.success() {
        panic!(
            "failed to deinterlace tray icon {} via TIFF",
            source.display()
        );
    }

    let to_png = Command::new("sips")
        .arg("-s")
        .arg("format")
        .arg("png")
        .arg(&tiff)
        .arg("--out")
        .arg(dest)
        .status()
        .unwrap_or_else(|error| panic!("failed to run sips for tray PNG export: {error}"));
    let _ = fs::remove_file(&tiff);
    if !to_png.success() {
        panic!("failed to write deinterlaced tray icon {}", dest.display());
    }
}
