use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    sync_codex_icon();
    generate_runtime_modules();
    tauri_build::build();
}

fn runtime_src_dir(manifest_dir: &Path) -> PathBuf {
    manifest_dir.join("../runtime")
}

fn runtime_modules_manifest(manifest_dir: &Path) -> PathBuf {
    manifest_dir.join("../runtime/index.json")
}

fn is_runtime_module_file(file_name: &str) -> bool {
    file_name.ends_with(".js")
        && !file_name.ends_with(".test.js")
        && !file_name.starts_with("_test")
}

fn generate_runtime_modules() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let runtime_dir = runtime_src_dir(&manifest_dir);
    let manifest_path = runtime_modules_manifest(&manifest_dir);

    println!("cargo:rerun-if-changed={}", manifest_path.display());
    println!("cargo:rerun-if-changed={}", runtime_dir.display());

    let manifest_raw = fs::read_to_string(&manifest_path)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", manifest_path.display()));
    let bundle_modules: Vec<String> = serde_json::from_str(&manifest_raw).unwrap_or_else(|error| {
        panic!(
            "failed to parse runtime modules manifest {}: {error}",
            manifest_path.display()
        )
    });

    let mut standalone_modules = Vec::new();
    for entry in fs::read_dir(&runtime_dir).unwrap_or_else(|error| {
        panic!(
            "failed to read runtime source directory {}: {error}",
            runtime_dir.display()
        )
    }) {
        let entry = entry.unwrap_or_else(|error| panic!("failed to read module entry: {error}"));
        let path = entry.path();
        let file_name = path
            .file_name()
            .and_then(|value| value.to_str())
            .unwrap_or("");
        if !is_runtime_module_file(file_name) {
            continue;
        }
        if bundle_modules.iter().any(|module| module == file_name) {
            continue;
        }
        standalone_modules.push(file_name.to_string());
    }
    standalone_modules.sort();

    let mut generated =
        String::from("// @generated by build.rs from runtime/index.json and runtime/*.js\n");
    generated.push_str("pub const RUNTIME_MODULE_SOURCES: &[&str] = &[\n");
    for file_name in &bundle_modules {
        let module_path = runtime_dir.join(file_name);
        if !module_path.is_file() {
            panic!(
                "runtime module listed in {} was not found: {}",
                manifest_path.display(),
                module_path.display()
            );
        }
        println!("cargo:rerun-if-changed={}", module_path.display());
        generated.push_str(&format!(
            "    include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../runtime/{file_name}\")),\n"
        ));
    }
    generated.push_str("];\n\n");
    generated.push_str("pub const STANDALONE_RUNTIME_SCRIPTS: &[&str] = &[\n");
    for file_name in &standalone_modules {
        let module_path = runtime_dir.join(file_name);
        println!("cargo:rerun-if-changed={}", module_path.display());
        generated.push_str(&format!(
            "    include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../runtime/{file_name}\")),\n"
        ));
    }
    generated.push_str("];\n");

    let generated_path = out_dir.join("runtime_modules.rs");
    fs::write(&generated_path, generated)
        .unwrap_or_else(|error| panic!("failed to write {}: {error}", generated_path.display()));
}

fn sync_codex_icon() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let codex_app_path =
        env::var("CODEX_APP_PATH").unwrap_or_else(|_| "/Applications/Codex.app".to_string());
    let codex_icon_source = PathBuf::from(codex_app_path)
        .join("Contents")
        .join("Resources")
        .join("icon.icns");

    if !codex_icon_source.is_file() {
        panic!("Codex icon not found: {}", codex_icon_source.display());
    }

    let icons_dir = manifest_dir.join("icons");
    fs::create_dir_all(&icons_dir)
        .unwrap_or_else(|error| panic!("failed to create {}: {error}", icons_dir.display()));

    let tauri_icon_png = icons_dir.join("icon.png");
    let status = Command::new("sips")
        .arg("-s")
        .arg("format")
        .arg("png")
        .arg(&codex_icon_source)
        .arg("--out")
        .arg(&tauri_icon_png)
        .status()
        .unwrap_or_else(|error| panic!("failed to run sips for Codex icon conversion: {error}"));

    if !status.success() {
        panic!(
            "failed to convert Codex icon {} to {}",
            codex_icon_source.display(),
            tauri_icon_png.display()
        );
    }

    println!("cargo:rerun-if-changed=CODEX_APP_PATH");
    println!("cargo:rerun-if-changed={}", codex_icon_source.display());
}
